service: hungry

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    STAGE: ${self:custom.stage}

plugins:
  - serverless-export-env

custom:
  stage: ${opt:stage, self:provider.stage}
  export-env:
    overwrite: true

functions:
  get-index:
    handler: src/functions/get-index.handler
    events:
      - http:
          path: /
          method: get
  get-restaurants:
    handler: src/functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants
          method: get
    environment:
      RESTAURANTS_TABLE: !Ref RestaurantsTable

resources:
  Resources:
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
  Outputs:
    RestaurantsTableName:
      Value: !Ref RestaurantsTable
